llmariner/llmariner

docs/developments/nvidia-gpu-operator-kind.md
Just minor personal preference.
=> Make a minor fix to docs

hack/dashboard/Dashboard.py, hack/dashboard/README.md, hack/dashboard/pages/1_Chat.py, hack/dashboard/pages/2_Fine_Tuning.py, hack/dashboard/requirements.txt
=> Add a simple dashboard

hack/deploy.sh, hack/deploy_fake_gpu_operator.sh
Used for local development with no GPU.
=> Add a deployment script for fake GPU operator

aws/playbook.yml
=> Add tags to a task for setting up kind cluster

hack/job-manager-dispatcher-values.yaml
To follow https://github.com/llm-operator/job-manager/pull/92.
=> Update the helm values of job-manager-dispatcher

.github/workflows/ci-post-merge.yml
=> Fix github workflow

aws/playbook.yml, aws/scripts/setup-databases.sh, aws/scripts/setup-minio-bucket.sh
This is analogous to hack/deploy.sh but using ansible functionalities.
=> Add demo llm-operator setup.

deployments/llm-operator/Chart.yaml, hack/llm-operator-values.yaml
Also remove unnecessary value defintions.
=> Bump helm chart versions

aws/README.md
kubernetes.core.k8s` module for Ansible is required.
=> Update aws/README.md for the required Ansible module

hack/llm-operator-values-nvidia-launchpad.yaml
=> Add a helm value for nvidia launchpad

aws/scripts/setup-kind-cluster.sh
gpu-operator install and manage device-plugin
=> Remove device-plugin installation from the nvkind setup script

hack/mlflow/README.md, hack/mlflow/test_endpoint.py
I don't fully understand this yet.
=> Add an example for MLflow Deployments Server

hack/mlflow/README.md
Just a quick link for the following:
- Run an MLflow Project on Kubernetes
- Authentication & Authorization
=> Add more notes on MLFlow

aws/playbook.yml, hack/deploy.sh
This namespace is needed to run a fine-tuning job
=> Create the 'example-org' namespace

aws/playbook.yml, deployments/llm-operator/Chart.yaml, hack/deploy.sh
Change the default org name to 'default'.
=> Do not create the namespace for the org

hack/kong_values.yaml, hack/llm-operator-values.yaml, hack/mlflow/deployment-server.yaml
=> Remove 'kong-' prefix

hack/llm-operator-values.yaml
Used in the tutorial for fine-tuning.
=> Add back google-gemma-2b-it

tutorial/getting_started.ipynb, tutorial/getting_started.md
=> Remove hyperparameter from tutorial

hack/llmo-dev/README.md, hack/llmo-dev/deploy_cert_manager.sh, hack/llmo-dev/deploy_external_dns.sh, hack/llmo-dev/deploy_llm_operator.sh, hack/llmo-dev/kong_plugin.yaml, hack/llmo-dev/letsencrypt-clusterissuer-prod.yaml, hack/llmo-dev/letsencrypt-clusterissuer-staging.yaml, hack/llmo-dev/llm-operator-values-llmo-dev.yaml
The scripts set up an endpoint with https://api.dev.llmo.cloudnatix.com (running inside a Kind cluster).
=> Add scripts for setting up an externally reachable endpoint

aws/playbook.yml
=> Remove the task for setting up the helm chart repo for llm-operator in the Ansible playbook

hack/llmo-demo/README.md, hack/llmo-demo/control-plane/README.md, hack/llmo-demo/control-plane/certificate.yaml, hack/llmo-demo/control-plane/deploy_cert_manager.sh, hack/llmo-demo/control-plane/deploy_llm_operator.sh, hack/llmo-demo/control-plane/inference_manager_server_service.yaml, hack/llmo-demo/control-plane/kong_plugin.yaml, hack/llmo-demo/control-plane/letsencrypt-clusterissuer-prod.yaml, hack/llmo-demo/control-plane/letsencrypt-clusterissuer-staging.yaml, hack/llmo-demo/control-plane/llm-operator-values.yaml, hack/llmo-demo/control-plane/session_manager_server_service.yaml, hack/llmo-demo/worker-plane/README.md, hack/llmo-demo/worker-plane/deploy_llm_operator.sh, hack/llmo-demo/worker-plane/llm-operator-values.yaml
This one is different from the llmo-dev configuration in such a way that a control plane and a worker plane are separated.
=> Add configuration for the demo env

hack/kong_values.yaml
Fix a bug introduced by a previous PR.
=> Fix redundant proxy definition in kong_values.yaml

hack/llmo-demo/worker-plane/llm-operator-values.yaml
Add the following models:
- deepseek-ai/deepseek-coder-6.7b-base-q4
- deepseek-ai/deepseek-coder-6.7b-base
=> Add more models to llmo-demo

hack/open-webui/README.md, hack/open-webui/open-webui.yaml
We might want to use this for a demo.
=> Add a test deployment for Open WebUI

hack/llm-operator-values.yaml
To exercise the leader election code.
=> Increase the replicaCount of inference-manager-engine to 2

hack/llm-operator-values.yaml, hack/llmo-demo/worker-plane/llm-operator-values.yaml
Use the new model config format.
=> Update the demo worker plane values.yaml

hack/llm-operator-values.yaml
=> Update the llmEngineAddr in hack/llm-operator-values.yaml

hack/llmo-demo/control-plane/deploy_llm_operator.sh, hack/llmo-demo/control-plane/llm-operator-values.yaml, hack/llmo-demo/worker-plane/deploy_llm_operator.sh, hack/llmo-demo/worker-plane/llm-operator-values.yaml
Follow the updated values.yaml definitions.
=> Update llmo-demo config

deployments/llm-operator/values.yaml, hack/llm-operator-values.yaml, scripts/update_chart.py
=> Make a minor change to keep the repos in the alphabetic order

.github/workflows/manual-integration-test.yaml, provision/local-cpu-only/deploy_llmariner.sh, provision/local-cpu-only/validate_deployment.sh
- Use the locally built chart
- Run the CLI commands
=> Improve the integration test

README.md
With the grammar check in Google Docs.
=> docs: make small tweaks to README.md

tutorials/README.md
=> docs: update README.md

hack/deploy_seaweedfs.sh
redundant port definition in `kubectl port-forward`
=> docs: fix a minor bug in deploy_seaweedfs.sh

provision/common/llmariner-values.yaml
We need to set here as the default value is set to empty.
=> fix(provision): set staticPasswords

deployments/llmariner/Chart.yaml
integration test: https://github.com/llmariner/llmariner/actions/runs/11883456285/job/33110240281
=> feat(chart): support dependency conditions

hack/llmo-demo/worker-plane/llmariner-values.yaml
=> fix: fix a typo in hack/llmo-demo/worker-plane/llmariner-values.yaml

deployments/llmariner/Chart.yaml
test: https://github.com/llmariner/llmariner/actions/runs/12004360386
=> feat(chart): bump up llmariner dependencies

.github/workflows/manual-integration-test-multi-cluster.yaml, provision/dev/README.md, provision/dev/helmfile.yaml
test: https://github.com/llmariner/llmariner/actions/runs/12174441912/job/33956435956
=> feat: add a prometheus scrap config for vLLM

cli/internal/admin/clusters/clusters.go
Also simplify the output of "admin clusters list" and do not show all the health details. Use "admin clusters get" for the information.
=> feat(cli): add "admin clusters get"

deployments/llmariner/Chart.yaml, provision/dev/values/tenant-control-plane.yaml
Forgot to update in a previous commit.
Also made a fix to tenant-control-plane.yaml.
=> feat(chart): bump job-manager-syncer

provision/dev/README.md, provision/dev/values/llmariner-control-plane.yaml
test: https://github.com/llmariner/llmariner/actions/runs/13275296891/job/37063656960
=> chore: disable unused default cluster

hack/demo/gpu-federation/README.md, hack/demo/gpu-federation/llmarine-tenant-cluster-values.yaml, hack/demo/gpu-federation/llmarine-worker-cluster-values.yaml, hack/demo/gpu-federation/set_up_kind_based_env.sh, hack/demo/gpu-federation/tear_down_kind_based_env.sh
Initial PR. Just set up kind clusters.
=> docs: add a gpu federation demo setup

deployments/llmariner/Chart.yaml
Leftover from the previous change.
=> feat(chart): bump job-manager-dispatcher to 1.14.0
