deployments/llm-operator/Chart.yaml

Picking the latest version was error-prone. For example, if we make a change to the job-manager helm charts, we need to take the following steps:
1. Open and merge a PR in the job-manage repo
2. Wait wait for the post CI workflow completes
3. Open some PR in the llm-operator repo
4. Make the post CI workflow build a new helm chart from the latest version
It is better to explicitly specify versions and open a PR to pick up the latest version.

Fix the version of depending Helm charts

---

hack/llm-operator-values.yaml

Enable this again once we have updated all testing script to support it (e.g., installation of rbac-manager).

Temporarily disable auth

---

.github/workflows/ci-post-merge.yml

To omit the 'v' prefix from Helm chart versions.

Use new_version instead of new_tag in ci-post-merge.yml

---

tutorial/getting_started.ipynb
tutorial/getting_started.md

It is difficult to see a concrete improvement, but using a prompt for LLM Operator API endpoint as an example.
Prompt:
- You are an text to API endpoint translator. Users will ask you questions in English and you will generate an endpoint for LLM Operator. What is the API endpoint for listing models?
Answer without fine-tuning:
- /api/llmoperator/models
Answer with fine-tuning:
- GET request to /v1/models. No parameter is needed. You will receive all the models in the system.SBATCH.default. trouveramodel=true.SBATCH.default.timeout=600.

Improve the fine-tuning tutorial

---

hack/llm-operator-values.yaml

To avoid downloading too many models.
llm-operator-values-nvidia-launchpad.yaml is used to download all available models.

Load only one model by default

---

hack/llm-operator-values-nvidia-launchpad.yaml
hack/llm-operator-values.yaml

We need to reserve one GPU for a fine-tuning job.

Do not allocate GPU to inference-manager-engine for tutorial

---

deployments/llm-operator/values.yaml

Having the "llm-operator-"  prefix follows the Helm convention, but it was making names unnecessarily long.
Follow https://github.com/helm/helm/issues/8354.

Avoid adding the 'llm-operator-' prefix

---

aws/scripts/setup-kind-cluster.sh
hack/kind-cluster.yaml

This works only with the lates kind, which can builds a v1.30 cluster.

Enable the 'PortForwardWebsockets' feature flag

---

hack/llmo-dev/README.md
hack/llmo-dev/llm-operator-values-llmo-dev.yaml

Also the actual value is also updated in Okta, the value that can be found in the commit history no longer works.

Replace clientSecret to a fake value

---

aws/playbook.yml
hack/deploy_kong.sh
hack/kong_internal_values.yaml

This is used to route requests for Jupyter Notebooks.
The original Kong receives a request for "/v1/sessions" and routes it to Session Manager Server/Agent. Then Session Manager Agent routes the request to this internal Kong with the same URL ("/v1/sessions").
Originally we are planning to make Session Manager truncate "/v1/sessions/<cluster ID>", but that didn't work. Jupyter Notebook didn't work when its ServerApp.base_url is different from the user visible path.

Add another kong for internal ingress controller

---

hack/minio.yaml
hack/multi-cluster/deploy_control_plane.sh
hack/multi-cluster/inference_manager_server_service.yaml
hack/multi-cluster/kind_cluster_control_plane.yaml
hack/multi-cluster/llm-operator-values-worker-plane.yaml

As it seems Kong does not support gRPC streaming, we need to make the engine directly hit the server with NodePort.

Use a NodePort to send gRPC streaming requests

---

hack/kind-cluster.yaml

I was using port 80 for the endpoint port when using a local Kong, but this no longer works as Session Manager expects 8080 for the redirect URL.
We can change the Dex and Session Manager configuration, but it was simpler to just use port 8080 consistently.

Use port 8080 as the endpoint port for a local Kong

---

hack/llmo-demo/control-plane/README.md
hack/llmo-demo/control-plane/llm-operator-values.yaml
hack/llmo-demo/control-plane/ollama.yaml

Used by vector-store-manager as a replacement of inference-manager-engine.

Deploy ollama in the control plane

---

hack/deploy_fake_gpu_operator.sh

The latest one was causing a pod crashloop due to lack of configmap.

Pin the version of fake GPU operator

---

aws/scripts/setup-kind-cluster.sh
hack/deploy_monitoring.sh

I don't think we can/should install prometheus-operator and regular prometheus at the same time.

Remove prometheus operator installation from deploy_monitoring.sh

---

hack/milvus_cluster_values.yaml

standalone mode does not work with s3. setup a cluster mode milvus and it works with s3.

setup milvus cluster using s3

---

hack/llmo-demo/control-plane/llm-operator-values.yaml

If we don't specify 'scopes' here, Dex does not add `offline_access` to the scope even if the client is asking for a refresh token.
https://github.com/dexidp/dex/blob/master/connector/oidc/oidc.go#L251 is the relevant code location in Dex.

Set scopes in dex OIDC configuration

---

hack/llmo-demo/worker-plane/llm-operator-values.yaml

70B didn't work in a single VM with a NCCL invalid_argument error.
It works when a node is provisioned with Karpenter.

Update demo worker config to preload Llama3.1-8B

---

hack/llm-operator-values.yaml
hack/llmo-demo/worker-plane/llm-operator-values.yaml

We used to have just q4, but q4_0 is more appropriate.

Fix model names for Q4_0 quantization

---

hack/llm-operator-values.yaml

This change depends on https://github.com/llm-operator/session-manager/pull/57 and https://github.com/llm-operator/cli/pull/122, but simplifies the overall configuration. (There is less dependency to the ingress controller URL in the configuration.)

Set oidcIssuerUrl to http://localhost:8080/v1/dex in the local testing

---

hack/llm-operator-values.yaml

Just use global.ingress.controllerUrl for issuer URL and callback URL.

Further simplify hack/llm-operator-values.yaml

---

cli/internal/accesstoken/api_key.go
cli/internal/http/http.go
cli/internal/k8s/k8s.go
cli/internal/runtime/env.go

Set env var LLMARINER_API_KEY to use the API key for authorization instead of an access token generated with "llma auth login".
This is useful when we run the CLI commnads from integration test.

Be able to run CLI commands with API keys

---

.github/workflows/pr-labeler.yml

To grant write access for pull requests coming from forked repositories, modify the action trigger from `pull_request` to `pull_request_target`.

ci(pr-labeler): change trigger to pull_request_target

---

provision/dev/minio_create_apikey.sh

The command was missing ":" and was attempting to set up the port fowarding for the same port twice (and failed).

fix(provision): fix a typo in the port-fowarding command

---

deployments/llmariner/templates/secrets.yaml
provision/dev/README.md
provision/dev/helmfile.yaml
provision/dev/minio_create_apikey.sh
provision/dev/minio_service.yaml

- install fake GPU cluster in the worker-plane cluster
- create a NodePort service for MinIO so that the worker plane can access
- set the context to the contro-plane cluster when running minio_create_apikey.sh
- change 'presync' to 'postsync' for applying control_plane_service.yaml as the 'llmariner-wp' namespace needs to be created first
- fix the secret key

fix(provision): fix multi-cluster provision

---

.github/workflows/manual-integration-test-multi-cluster.yaml

Just check model loading. The runner doesn't have suffient resources.

ci: do not run inference in manual-integration-test-multi-cluster

---

deployments/llmariner/values.yaml
provision/common/llmariner-values.yaml

This is required once we don't set the default value.

fix(chart): do not set s3.endpointUrl in values.yaml

---

deployments/llmariner/Chart.yaml

- dex-server, rbac-server: 1.2.0 -> 1.3.0
- inference-manager-{engine,server}: 1.7.0 -> 1.8.0
- user-manager: 1.2.0 -> 1.4.0

feat(chart): bump versions

---

cli/internal/time/age.go
cli/internal/time/age_test.go

Avoid "0y" when an age is > 7 days.

fix(cli): make toAge() use the d format for less than one year case

---

provision/dev/keda-helmfile.yaml

To disable KEDA by default, added a separate Helmfile. This will be used in inference script like below:
```console
helmfile apply -f keda-helmfile.yaml
```

feat(helm): add an optional keda helmfile for inference autoscaling

---

hack/inferentia.md

We need Karpenter 1.1.0 or later to provision inf2 nodes by requesting the neuroncore resources.

docs(hack): clarify the karpenter version for inf2 support

---

cli/internal/context/context.go

This often happens when there is some misconfiguration (e.g., ~/.config/llmariner/config.yaml has a old deleted org/project). Nice to have a clear error message.

chore: improve the error message when a login user doesn't belong to any org/project

---

deployments/llmariner/Chart.yaml
provision/dev/llmariner_values.yaml

Update llmariner_values.yaml for the new defaultApiKeys format.

feat(chart): bump user-manager version

---

.github/workflows/manual-integration-test-gpu-federation.yaml

Currently job-manager-syncer gets a list of clusters at its initialization time.

test: set up a tenant cluster after a worker cluster

---

provision/dev/README.md

Unregister the default cluster to avoid an error from job-manager-syncer.

docs: update the setup instruction for GPU federation

---

cli/internal/accesstoken/accesstoken.go

Extra() returns an empty string when a token is generated from a refresh token.

fix: make saveToken get values directly from token fields

---

cli/internal/storage/files/files.go

This simplifies the interface. Also users can use any buckets as long as it is accessible from job-manager-dispatcher.
Depend on https://github.com/llmariner/job-manager/pull/411

feat(cli): change 'file create-link' to take an S3 bucket name

---

provision/dev/helmfile.yaml.gotmpl

https://hub.docker.com/r/bitnami/minio no longer provides images.

fix: change the bitnami repos to use bitnamilegacy
